### ISSUE TITLE
Not opening 

### ISSUE THREAD

**Issue by Gruntfuggly** [auchenberg/vscode-open-file-folder#1]
Hi there

I was looking for this functionality and found your extension. Unfortunately it wasn't working for me.

However, it works if I change the line 8 to:

        let filepath = vscode.Uri.parse( vscode.window.activeTextEditor.document.uri.path ).fsPath;
        let folderName = path.dirname( filepath );

**Comment by auchenberg** [comment]
Fixed in https://github.com/auchenberg/vscode-open-file-folder/commit/85079a0549f537d5c67524b22c16bf93d1abe32b.

A new release has been published. Let me know how it works!
